using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GuiBase.Models
{
    public static class TranslateCommonId
    {
        public static readonly string LogonId = "G_Text_Logon";
        public static readonly string AlarmId = "G_Text_Alarm";
        public static readonly string HistoryAlarmId = "G_Text_HistoryAlarm";
        public static readonly string OperRecordId = "G_Text_OperRecord";
        public static readonly string ExitId = "G_Text_Exit";
        public static readonly string OverViewId = "G_Text_OverView";
        public static readonly string L1ViewId = "G_Text_L1View";
        public static readonly string L2ViewId = "G_Text_L2View";
        public static readonly string L3ViewId = "G_Text_L3View";
        public static readonly string CommandId = "G_Text_Command";
        public static readonly string OtherId = "G_Text_Other";
        public static readonly string GoForwardId = "G_Text_GoForward";
        public static readonly string GoBackId = "G_Text_GoBack";
        public static readonly string AccManagerId = "G_Text_AccManager";
        public static readonly string SignalMonitorId = "G_Text_SignalMonitor";
        public static readonly string DeviceConfigId = "G_Text_DeviceConfig";
        public static readonly string AlarmNameId = "G_Text_AlarmName";
        public static readonly string PartNameId = "G_Text_PartName";
        public static readonly string AlarmLevelId = "G_Text_AlarmLevel";
        public static readonly string DescriptionId = "G_Text_Description";
        public static readonly string GroupId = "G_Text_Group";
        public static readonly string AppearTimeId = "G_Text_AppearTime";
        public static readonly string CountsId = "G_Text_Counts";
        public static readonly string ConfirmId = "G_Text_Confirm";
        public static readonly string SystemManagementId = "G_Text_SystemManagement";
        public static readonly string UserManagementId = "G_Text_UserManagement";
        public static readonly string RoleManagementId = "G_Text_RoleManagement";
        public static readonly string ResourceManagementId = "G_Text_ResourceManagement";
        public static readonly string UserNameId = "G_Text_UserName";
        public static readonly string AccountId = "G_Text_Account";
        public static readonly string AddId = "G_Text_Add";
        public static readonly string IdId = "G_Text_Id";
        public static readonly string NameId = "G_Text_Name";
        public static readonly string SexId = "G_Text_Sex";
        public static readonly string StatusId = "G_Text_Status";
        public static readonly string CreateTimeId = "G_Text_CreateTime";
        public static readonly string CreateIdId = "G_Text_CreateId";
        public static readonly string OperateId = "G_Text_Operate";
        public static readonly string EditId = "G_Text_Edit";
        public static readonly string DeleteId = "G_Text_Delete";
        public static readonly string RolesId = "G_Text_Roles";
        public static readonly string PasswordId = "G_Text_Password";
        public static readonly string CancelId = "G_Text_Cancel";
        public static readonly string ResourceNameId = "G_Text_ResourceName";
        public static readonly string DisableId = "G_Text_Disable";
        public static readonly string ParentNameId = "G_Text_ParentName";
        public static readonly string ParentIdId = "G_Text_ParentId";
        public static readonly string EndTimeId = "G_Text_EndTime";
        public static readonly string DurationId = "G_Text_Duration";
        public static readonly string OldPasswordId = "G_Text_OldPassword";
        public static readonly string NewPasswordId = "G_Text_NewPassword";
        public static readonly string ConfirmPasswordId = "G_Text_ConfirmPassword";
        public static readonly string OKId = "G_Text_OK";
        public static readonly string AlarmGroupId = "G_Text_AlarmGroup";
        public static readonly string DeviceNameId = "G_Text_DeviceName";
        public static readonly string DeviceTypeId = "G_Text_DeviceType";
        public static readonly string LanguageSelectId = "G_Text_LanguageSelect";
        public static readonly string FilterConditionId = "G_Text_FilterCondition";
        public static readonly string MainViewId = "G_Text_MainView";
        public static readonly string QueryId = "G_Text_Query";
        public static readonly string TotalId = "G_Text_Total";
        public static readonly string EmptyValueId = "G_Text_EmptyValue";
        public static readonly string PasswordHelperId = "G_Text_PasswordHelper";
        public static readonly string LogonFaliMessageId = "G_Text_LogonFaliMessage";
        public static readonly string SelectId = "G_Text_Select";
        public static readonly string WaringId = "G_Text_Warning";
        public static readonly string DeleteResourceWarningId = "G_Text_DeleteResourceWarning";
        public static readonly string DeleteResourceFailId = "G_Text_DeleteResourceFail";
        public static readonly string DisableResourceWarningId = "G_Text_DisableResourceWarning";
        public static readonly string DisableResourceFailId = "G_Text_DisableResourceFail";
        public static readonly string EnableResourceFailId = "G_Text_EnableResourceFail";
        public static readonly string ParentIdSetErrorId = "G_Text_ParentIdSetError";
        public static readonly string CreateResourceErrorId = "G_Text_CreateResourceError";
        public static readonly string UpdateResourceErrorId = "G_Text_UpdateResourceError";
        public static readonly string ResourceListId = "G_Text_ResourceList";
        public static readonly string ResourceNameListId = "G_Text_ResourceNameList";
        public static readonly string ResourceNameSetErrorId = "G_Text_ResourceNameSetError";
        public static readonly string DeleteRoleWarningId = "G_Text_DeleteRoleWarning";
        public static readonly string DeleteRoleFailId = "G_Text_DeleteRoleFail";
        public static readonly string DisableRoleWarningId = "G_Text_DisableRoleWarning";
        public static readonly string DisableRoleFailId = "G_Text_DisableRoleFail";
        public static readonly string EnableRoleFailId = "G_Text_EnableRoleFail";
        public static readonly string AssignId = "G_Text_Assign";
        public static readonly string UserDetailedId = "G_Text_UserDetailed";
        public static readonly string ChangePasswordErrorId = "G_Text_ChangePasswordError";
        public static readonly string ChangePasswordError1Id = "G_Text_ChangePasswordError1";
        public static readonly string ChangePasswordId = "G_Text_ChangePassword";
        public static readonly string LogoutId = "G_Text_Logout";
        public static readonly string UserEditId = "G_Text_UserEdit";
        public static readonly string DisableUserWarningId = "G_Text_DisableUserWarning";
        public static readonly string DisableUserFailId = "G_Text_DisableUserFail";
        public static readonly string EnableUserFailId = "G_Text_EnableUserFail";
        public static readonly string DeleteUserWarningId = "G_Text_DeleteUserWarning";
        public static readonly string DeleteUserFailId = "G_Text_DeleteUserFail";
        public static readonly string RoleEditId = "G_Text_RoleEdit";
        public static readonly string ResourceEditId = "G_Text_ResourceEdit";
        public static readonly string ResourceAssignId = "G_Text_ResourceAssign";
        public static readonly string UnknownId = "G_Text_Unknown";
        public static readonly string NotConnectId = "G_Text_NotConnect";
        public static readonly string BadQualityId = "G_Text_BadQuality";
        public static readonly string DeviceStatusId = "G_Text_DeviceStatus";
        public static readonly string ButtonOperDescId = "G_Text_ButtonOperDesc";
        public static readonly string AlarmConfirmOperDescId = "G_Text_AalrmConfirmOperDesc";
        public static readonly string SuccessfulId = "G_Text_Successful";
        public static readonly string FailId = "G_Text_Fail";
        public static string TimeId = "G_Text_Time";
        internal static string ComputerInforId= "G_Text_ComputerInfor";
        internal static string MessageId= "G_Text_Message";
        internal static string ResetId = "G_Text_Reset";

    }
}
